USE [master]
GO

/****** Object:  Database [eddb1]    Script Date: 26-01-2019 16:49:38 ******/
CREATE DATABASE [eddb1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eddb1', FILENAME = N'd:\\Data\\Galaxy\\eddb1.mdf' , SIZE = 6000MB , MAXSIZE = 10000MB , FILEGROWTH = 100MB)
 LOG ON 
( NAME = N'eddb1_Log', FILENAME = N'd:\\Data\\Galaxy\\eddb1.ldf' , SIZE = 200MB , MAXSIZE = 5000MB , FILEGROWTH = 100MB)


ALTER DATABASE [eddb1] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eddb1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eddb1] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [eddb1] SET ANSI_NULLS ON 
GO

ALTER DATABASE [eddb1] SET ANSI_PADDING ON 
GO

ALTER DATABASE [eddb1] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [eddb1] SET ARITHABORT ON 
GO

ALTER DATABASE [eddb1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eddb1] SET AUTO_SHRINK ON
GO

ALTER DATABASE [eddb1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eddb1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eddb1] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [eddb1] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [eddb1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eddb1] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [eddb1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eddb1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eddb1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eddb1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eddb1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eddb1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eddb1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eddb1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eddb1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eddb1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [eddb1] SET  MULTI_USER 
GO

ALTER DATABASE [eddb1] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [eddb1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eddb1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eddb1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [eddb1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [eddb1] SET QUERY_STORE = OFF
GO

USE [eddb1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [eddb1] SET  READ_WRITE 
GO


